### ISSUE TITLE
Docker image to run REalTabFormer to support NVIDIA CUDA and GPU

### ISSUE THREAD

**Issue by echatzikyriakidis** [worldbank/REaLTabFormer#38]
Hi @avsolatorio,

I was wondering if you have any latest docker image example from NVIDIA to support running a Python application with REalTabFormer that will utilize GPU from host machine.

Thanks!

**Comment by echatzikyriakidis** [comment]
I am thinking also to run the application in a Kubernetes cluster.

**Comment by avsolatorio** [comment]
Hello @echatzikyriakidis, Unfortunately, this is beyond the scope of support we see for the project at the moment. I am pretty sure there are a lot of resources out there for this. I encourage you to contribute your solution back here for others to benefit from as well. Thank you! 😀

**Comment by echatzikyriakidis** [comment]
Thank you!

Here is how I have managed to containerize it:

With docker run:

```
docker run --gpus 1 --rm -it --name container_name image_name:latest
```

With docker compose:

```
services:
  application:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
